language: erlang

otp_release:
    - 17.0

env:
      global:
             # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
             #   via the "travis encrypt" command using the project repo's public key
             - secure: "sbGXW2TBEElKhvOsUGo+7JUSrfq4x1H6LhCzD1yUCsM6xw9osq1As8rrN+J6Run0JIM1Tf1dMyfACPKqr6/JHjl9a97RJKdvTAEIhNOy4/mDV7eufMGCKgPpRFa8NLuFP1/RgkU4rbhO6qPOVVsr7lFFXjrSSwpyXrNNupP8dW0="
             - ELIXIR_VERSION=1.0.2

before_install:
    - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
    - unzip -d elixir Precompiled.zip

before_script:
    - export PATH=`pwd`/elixir/bin:$PATH

addons:
      coverity_scan:
             project:
                name: "fhunleth/elixir_ale"
                description: "Elixir port of Erlang/ALE"
             notification_email: fhunleth@troodon-software.com
             build_command: "make"
             branch_pattern: coverity_scan

script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make ; fi
