language: erlang

otp_release:
    - 17.0

env:
      global:
             # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
             #   via the "travis encrypt" command using the project repo's public key
             - secure: "S5hpRVpjLOt2xEJuOJLJYtpf4TqUwfh+mhaw0jBkfc0yiVNO8NfwKLrWYqNBYdbl8fF15a3C/KjCdZZ9RllH6F1N6jxtgWFmiU92DyKiMQVwekeK5NkT8mdB26WlhxdQMBsejheuVVYecQxxc6uDX15WoGy9lO0cxO3TIZKRVkw="

before_install:
    - wget https://github.com/elixir-lang/elixir/releases/download/v1.0.2/Precompiled.zip
    - unzip -d elixir Precompiled.zip

before_script:
    - export PATH=`pwd`/elixir/bin:$PATH

addons:
      coverity_scan:
             project:
                name: "fhunleth/elixir_ale"
                description: "Elixir port of Erlang/ALE"
             notification_email: fhunleth@troodon-software.com
             build_command: "make"
             branch_pattern: coverity_scan

script: make
